In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import os
import scipy.misc as misc
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.model_selection import cross_val_score
%matplotlib inline

In [2]:
def scale(img):
    return (img / 255.)

In [3]:
## 데이터 importing 
## label 을 1과 -1로 코딩

pwd = os.getcwd()
path = os.path.join(pwd,"extracted_images")
l1=os.listdir(path = path)

X_full=[]
Y_full=[]
label_list=[]

i=1

for dir in l1:
    if(dir[0]=="."): continue # skip .DS_
    path1 = os.path.join(path,dir)
    allfiles = os.listdir(path1)
    #print(dir)
    label_list.append(dir[0])
    j=0
    
    for file in allfiles:
        if(j>500): break
        if(file[0:3]==".DS"): continue
        t1 = os.path.join(path1,file)
        a1 = misc.imread(t1).flatten()
        X_full.append(scale(a1))
        Y_full.append(i)
        j+=1
        
    if i==1:
        i=-1

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:26: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.


In [4]:
## np.array
XX=np.array(X_full)
YY=np.array(Y_full)

In [5]:
## Split images
X_train,X_test,y_train,y_test = train_test_split(XX,YY,random_state=77,test_size=.15)

In [6]:
# minimum Constraint and linear kernel
svm_ini = svm.SVC(C=0.001,kernel='linear')
res_ini=cross_val_score(svm_ini,X_train,y_train)
print("No constraint,No kernel",res_ini)

No constraint,No kernel [ 0.98637187  0.98637057  0.98637057]


### polynomial kernel 적용

In [6]:
## cross validation을 통해 적절한 C 선택

c_list=[0.1,1,10,20,50]
cross_val=[]

for C in c_list:
    svm1=svm.SVC(C=C,kernel='poly')
    res=cross_val_score(svm1,X_train,y_train)
    print(res)

[ 0.98637187  0.98637057  0.98637057]
[ 0.98637187  0.98637057  0.98637057]
[ 0.98894501  0.98913458  0.98875334]
[ 0.99056514  0.98951582  0.99123141]
[ 0.99094635  0.98922989  0.99075486]


In [7]:
## model fitting with train data and prediction

## poly basis kernel
svm_model=svm.SVC(C=20,kernel='poly')
svm_model.fit(X_train,y_train)

predictions = svm_model.predict(X_test)
predictions = np.array(predictions)
print("percent accuracy (poly kernel): ",np.mean(predictions==y_test))

percent accuracy (poly kernel):  0.991539153915


### radial basis kernel 적용

In [10]:
## cross validation을 통해 적절한 C 선택

c_list=[1,10,20,50]
cross_val=[]

for C in c_list:
    svm1=svm.SVC(C=C,kernel='rbf')
    res=cross_val_score(svm1,X_train,y_train)
    print(res)

[ 0.98637187  0.98637057  0.98637057]
[ 0.9883732   0.9884674   0.98875334]
[ 0.99018393  0.98961113  0.99008769]
[ 0.99113695  0.98970644  0.99151735]


In [11]:
## model fitting with train data and prediction

## radial basis kernel
svm_model=svm.SVC(C=50,kernel='rbf')
svm_model.fit(X_train,y_train)

predictions = svm_model.predict(X_test)
predictions = np.array(predictions)
print("percent accuracy (rbf kernel): ",np.mean(predictions==y_test))

percent accuracy (rbf kernel):  0.992799279928


In [12]:
## support vector와, 클래스별 support vector 개수 출력
print ("get support_vectors_")
print (svm_model.support_vectors_)
print ("number of support vectors per class")
print (svm_model.n_support_)

get support_vectors_
[[ 0.98823529  1.          1.         ...,  1.          1.          1.        ]
 [ 1.          0.99215686  1.         ...,  1.          1.          1.        ]
 [ 1.          0.99607843  1.         ...,  1.          1.          1.        ]
 ..., 
 [ 1.          1.          1.         ...,  1.          1.          1.        ]
 [ 1.          1.          1.         ...,  1.          1.          1.        ]
 [ 1.          1.          1.         ...,  1.          1.          1.        ]]
number of support vectors per class
[1035  374]
